TLS security
hardcoreeng/meeting-service pull request #2
Opened 2021-10-26 10:20 UTC by haiodo

Signed-off-by: Andrey Sobolev <haiodo@gmail.com>

2021-10-26 11:59 UTC, sumboid requested changes
It seems `package-lock.json` was generated by `npm`? Let's get rid of it in such case, we already have the `yarn.lock`

2021-10-26 11:59 UTC, sumboid commented on .env
>  KMS_URL=ws://359.rocks:8888/kurento
BTW since file was changed, `359.rocks` also can be replaced to the `localhost`

2021-10-26 11:59 UTC, sumboid commented on distribution/docker-compose.yaml
> +      - 5000-5500:5000-5500
Seems to be part of kms and there are also unnecessary `-` and below

2021-10-26 15:09 UTC, haiodo commented on .env
>  KMS_URL=ws://359.rocks:8888/kurento
I've deployed with docker-compose only, so missed to rollback

2021-10-27 05:10 UTC, haiodo commented on distribution/docker-compose.yaml
> +      - 5000-5500:5000-5500
Fixed

2021-10-27 05:10 UTC, haiodo commented on .env
>  KMS_URL=ws://359.rocks:8888/kurento
Fixed

2021-10-27 05:39 UTC, sumboid approved these changes

2021-10-27 05:40 UTC, merged